nam: Branch merge rule check
on:
  workflow_call:
    inputs:
      allowed-branch-from:
        description: The source branch to use
        type: string
      allowed-branch-to:
        description: The target branch to use
        type: string
        required: false
        default: main
      runs-on:
        description: The runner to use
        type: string
        required: false
        default: ubuntu-24.04

jobs:
  check-branch:
    name: Check branch
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Check branch
        env:
          branch_from: ${{ github.head_ref }}
          branch_to: ${{ github.base_ref }}
          allowed_from: ${{ inputs.allowed-branch-from }}
          allowed_to: ${{ inputs.allowed-branch-to }}
        run: |
          if [["${branch_from}" == "${allowed_from}" && "${branch_to}" == "${allowed_to}"]]; then
            echo 'Branch merge rule check succeeded'
          else
            echo "Error: Only '${allowed_from}' can be merged into '${allowed_to}'"
            exit 1
          fi
