name: Run Terraform tests
on:
  workflow_call:
    inputs:
      root-dir:
        description: The root directory in which to run Terragrunt
        type: string
        required: false
        default: cloud
      terragrunt-commons-version:
        description: The version of terragrunt-commons to use
        type: string
        required: false
        default: v3
      tfenv-version:
        description: The version of tfenv to use
        type: string
        required: false
        default: 39d8c27ad9862ffdec57989b66fd2720cb72e76c  # commit 2023-12-19 / checked 2024-10-25
      tgenv-version:
        description: The version of tgenv to use
        type: string
        required: false
        default: 8f87cb3bd76063d6adef2413ce0a399f773f2319  # commit 2024-06-14 / checked 2024-10-25

    secrets:
      TERRAFORM_CREDENTIALS_HOSTNAME:
        description: The Terraform Cloud/Enterprise hostname to use
        required: false
      TERRAFORM_CREDENTIALS_TOKEN:
        description: The Terraform Cloud/Enterprise API token to use
        required: false

concurrency:
  group: ${{ github.workflow }}-terraform-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: logikal-io/run-logikal-playbook@v2
        with:
          roles: terraform
          vars: '{
            "tfenv_version": "${{ inputs.tfenv-version }}",
            "tgenv_version": "${{ inputs.tgenv-version }}",
            "terragrunt_commons_version": "${{ inputs.terragrunt-commons-version }}",
          }'

      - name: Install Terragrunt
        working-directory: ${{ inputs.root-dir }}
        run: tgenv install

      - name: Validate configuration
        working-directory: ${{ inputs.root-dir }}
        env:
          TERRAGRUNT_USE_CREDENTIALS: false
          CREDENTIALS_HOSTNAME: ${{ secrets.TERRAFORM_CREDENTIALS_HOSTNAME || 'app.terraform.io' }}
          CREDENTIALS_TOKEN: ${{ secrets.TERRAFORM_CREDENTIALS_TOKEN }}
        run: |-
          if [[ -n "${CREDENTIALS_TOKEN}" ]]; then
            hostname="$(echo "${CREDENTIALS_HOSTNAME}" | sed 's/\./_/g' | sed 's/-/__/g')"
            export "TF_TOKEN_${hostname}"="${CREDENTIALS_TOKEN}"
          fi
          terragrunt run-all validate --terragrunt-parallelism 1
